version: '3.7'

services:
  backend:
    build:
      context: .
    container_name: backend
    restart: on-failure
    ports:
      - "9000:9000"
    env_file:
      - ./.env
    networks:
      - plants
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
  database:
    image: mysql
    container_name: database
    restart: on-failure
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - ./mysql.env
    volumes:
     - database-data:/var/lib/mysql
    networks:
      - plants
    ports:
      - "5500:3306"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
networks:
  plants:
    name: plants
volumes:
  database-data:

